using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ChaChing.Test
{
    [TestClass]
    public class ConverterTests
    {
        [TestMethod]
        public void ZeroToHundred()
        {
            var tests = new Dictionary<int, string>
            {
                {0, "zero dollars"},
                {1, "one dollar"},
                {2, "two dollars"},
                {3, "three dollars"},
                {4, "four dollars"},
                {5, "five dollars"},
                {6, "six dollars"},
                {7, "seven dollars"},
                {8, "eight dollars"},
                {9, "nine dollars"},
                {10, "ten dollars"},
                {11, "eleven dollars"},
                {12, "twelve dollars"},
                {13, "thirteen dollars"},
                {14, "fourteen dollars"},
                {15, "fifteen dollars"},
                {16, "sixteen dollars"},
                {17, "seventeen dollars"},
                {18, "eighteen dollars"},
                {19, "nineteen dollars"},
                {20, "twenty dollars"},
                {21, "twenty-one dollars"},
                {22, "twenty-two dollars"},
                {23, "twenty-three dollars"},
                {24, "twenty-four dollars"},
                {25, "twenty-five dollars"},
                {26, "twenty-six dollars"},
                {27, "twenty-seven dollars"},
                {28, "twenty-eight dollars"},
                {29, "twenty-nine dollars"},
                {30, "thirty dollars"},
                {31, "thirty-one dollars"},
                {32, "thirty-two dollars"},
                {33, "thirty-three dollars"},
                {34, "thirty-four dollars"},
                {35, "thirty-five dollars"},
                {36, "thirty-six dollars"},
                {37, "thirty-seven dollars"},
                {38, "thirty-eight dollars"},
                {39, "thirty-nine dollars"},
                {40, "forty dollars"},
                {41, "forty-one dollars"},
                {42, "forty-two dollars"},
                {43, "forty-three dollars"},
                {44, "forty-four dollars"},
                {45, "forty-five dollars"},
                {46, "forty-six dollars"},
                {47, "forty-seven dollars"},
                {48, "forty-eight dollars"},
                {49, "forty-nine dollars"},
                {50, "fifty dollars"},
                {51, "fifty-one dollars"},
                {52, "fifty-two dollars"},
                {53, "fifty-three dollars"},
                {54, "fifty-four dollars"},
                {55, "fifty-five dollars"},
                {56, "fifty-six dollars"},
                {57, "fifty-seven dollars"},
                {58, "fifty-eight dollars"},
                {59, "fifty-nine dollars"},
                {60, "sixty dollars"},
                {61, "sixty-one dollars"},
                {62, "sixty-two dollars"},
                {63, "sixty-three dollars"},
                {64, "sixty-four dollars"},
                {65, "sixty-five dollars"},
                {66, "sixty-six dollars"},
                {67, "sixty-seven dollars"},
                {68, "sixty-eight dollars"},
                {69, "sixty-nine dollars"},
                {70, "seventy dollars"},
                {71, "seventy-one dollars"},
                {72, "seventy-two dollars"},
                {73, "seventy-three dollars"},
                {74, "seventy-four dollars"},
                {75, "seventy-five dollars"},
                {76, "seventy-six dollars"},
                {77, "seventy-seven dollars"},
                {78, "seventy-eight dollars"},
                {79, "seventy-nine dollars"},
                {80, "eighty dollars"},
                {81, "eighty-one dollars"},
                {82, "eighty-two dollars"},
                {83, "eighty-three dollars"},
                {84, "eighty-four dollars"},
                {85, "eighty-five dollars"},
                {86, "eighty-six dollars"},
                {87, "eighty-seven dollars"},
                {88, "eighty-eight dollars"},
                {89, "eighty-nine dollars"},
                {90, "ninety dollars"},
                {91, "ninety-one dollars"},
                {92, "ninety-two dollars"},
                {93, "ninety-three dollars"},
                {94, "ninety-four dollars"},
                {95, "ninety-five dollars"},
                {96, "ninety-six dollars"},
                {97, "ninety-seven dollars"},
                {98, "ninety-eight dollars"},
                {99, "ninety-nine dollars"}
            };
            var c = new Converter();
            foreach (var test in tests)
            {
                var result = c.ToWords(test.Key);
                Assert.AreEqual(test.Value, result);
            }
        }

        [TestMethod]
        public void Hundreds()
        {
            var dict = new Dictionary<int, string>
            {
                {100, "one hundred dollars"},
                {101, "one hundred one dollars"},
                {102, "one hundred two dollars"},
                {103, "one hundred three dollars"},
                {104, "one hundred four dollars"},
                {105, "one hundred five dollars"},
                {106, "one hundred six dollars"},
                {107, "one hundred seven dollars"},
                {108, "one hundred eight dollars"},
                {109, "one hundred nine dollars"},
                {110, "one hundred ten dollars"},
                {111, "one hundred eleven dollars"},
                {112, "one hundred twelve dollars"},
                {113, "one hundred thirteen dollars"},
                {114, "one hundred fourteen dollars"},
                {115, "one hundred fifteen dollars"},
                {116, "one hundred sixteen dollars"},
                {117, "one hundred seventeen dollars"},
                {118, "one hundred eighteen dollars"},
                {119, "one hundred nineteen dollars"},
                {120, "one hundred twenty dollars"},
                {121, "one hundred twenty-one dollars"},
                {122, "one hundred twenty-two dollars"},
                {123, "one hundred twenty-three dollars"},
                {124, "one hundred twenty-four dollars"},
                {125, "one hundred twenty-five dollars"},
                {126, "one hundred twenty-six dollars"},
                {127, "one hundred twenty-seven dollars"},
                {128, "one hundred twenty-eight dollars"},
                {129, "one hundred twenty-nine dollars"},
                {130, "one hundred thirty dollars"},
                {131, "one hundred thirty-one dollars"},
                {132, "one hundred thirty-two dollars"},
                {133, "one hundred thirty-three dollars"},
                {134, "one hundred thirty-four dollars"},
                {135, "one hundred thirty-five dollars"},
                {136, "one hundred thirty-six dollars"},
                {137, "one hundred thirty-seven dollars"},
                {138, "one hundred thirty-eight dollars"},
                {139, "one hundred thirty-nine dollars"},
                {140, "one hundred forty dollars"},
                {141, "one hundred forty-one dollars"},
                {142, "one hundred forty-two dollars"},
                {143, "one hundred forty-three dollars"},
                {144, "one hundred forty-four dollars"},
                {145, "one hundred forty-five dollars"},
                {146, "one hundred forty-six dollars"},
                {147, "one hundred forty-seven dollars"},
                {148, "one hundred forty-eight dollars"},
                {149, "one hundred forty-nine dollars"},
                {150, "one hundred fifty dollars"},
                {151, "one hundred fifty-one dollars"},
                {152, "one hundred fifty-two dollars"},
                {153, "one hundred fifty-three dollars"},
                {154, "one hundred fifty-four dollars"},
                {155, "one hundred fifty-five dollars"},
                {156, "one hundred fifty-six dollars"},
                {157, "one hundred fifty-seven dollars"},
                {158, "one hundred fifty-eight dollars"},
                {159, "one hundred fifty-nine dollars"},
                {160, "one hundred sixty dollars"},
                {161, "one hundred sixty-one dollars"},
                {162, "one hundred sixty-two dollars"},
                {163, "one hundred sixty-three dollars"},
                {164, "one hundred sixty-four dollars"},
                {165, "one hundred sixty-five dollars"},
                {166, "one hundred sixty-six dollars"},
                {167, "one hundred sixty-seven dollars"},
                {168, "one hundred sixty-eight dollars"},
                {169, "one hundred sixty-nine dollars"},
                {170, "one hundred seventy dollars"},
                {171, "one hundred seventy-one dollars"},
                {172, "one hundred seventy-two dollars"},
                {173, "one hundred seventy-three dollars"},
                {174, "one hundred seventy-four dollars"},
                {175, "one hundred seventy-five dollars"},
                {176, "one hundred seventy-six dollars"},
                {177, "one hundred seventy-seven dollars"},
                {178, "one hundred seventy-eight dollars"},
                {179, "one hundred seventy-nine dollars"},
                {180, "one hundred eighty dollars"},
                {181, "one hundred eighty-one dollars"},
                {182, "one hundred eighty-two dollars"},
                {183, "one hundred eighty-three dollars"},
                {184, "one hundred eighty-four dollars"},
                {185, "one hundred eighty-five dollars"},
                {186, "one hundred eighty-six dollars"},
                {187, "one hundred eighty-seven dollars"},
                {188, "one hundred eighty-eight dollars"},
                {189, "one hundred eighty-nine dollars"},
                {190, "one hundred ninety dollars"},
                {191, "one hundred ninety-one dollars"},
                {192, "one hundred ninety-two dollars"},
                {193, "one hundred ninety-three dollars"},
                {194, "one hundred ninety-four dollars"},
                {195, "one hundred ninety-five dollars"},
                {196, "one hundred ninety-six dollars"},
                {197, "one hundred ninety-seven dollars"},
                {198, "one hundred ninety-eight dollars"},
                {199, "one hundred ninety-nine dollars"},
                {200, "two hundred dollars"},
                {201, "two hundred one dollars"},
                {202, "two hundred two dollars"},
                {203, "two hundred three dollars"},
                {204, "two hundred four dollars"},
                {205, "two hundred five dollars"},
                {206, "two hundred six dollars"},
                {207, "two hundred seven dollars"},
                {208, "two hundred eight dollars"},
                {209, "two hundred nine dollars"},
                {210, "two hundred ten dollars"},
                {211, "two hundred eleven dollars"},
                {212, "two hundred twelve dollars"},
                {213, "two hundred thirteen dollars"},
                {214, "two hundred fourteen dollars"},
                {215, "two hundred fifteen dollars"},
                {216, "two hundred sixteen dollars"},
                {217, "two hundred seventeen dollars"},
                {218, "two hundred eighteen dollars"},
                {219, "two hundred nineteen dollars"},
                {220, "two hundred twenty dollars"},
                {221, "two hundred twenty-one dollars"},
                {222, "two hundred twenty-two dollars"},
                {223, "two hundred twenty-three dollars"},
                {224, "two hundred twenty-four dollars"},
                {225, "two hundred twenty-five dollars"},
                {226, "two hundred twenty-six dollars"},
                {227, "two hundred twenty-seven dollars"},
                {228, "two hundred twenty-eight dollars"},
                {229, "two hundred twenty-nine dollars"},
                {230, "two hundred thirty dollars"},
                {231, "two hundred thirty-one dollars"},
                {232, "two hundred thirty-two dollars"},
                {233, "two hundred thirty-three dollars"},
                {234, "two hundred thirty-four dollars"},
                {235, "two hundred thirty-five dollars"},
                {236, "two hundred thirty-six dollars"},
                {237, "two hundred thirty-seven dollars"},
                {238, "two hundred thirty-eight dollars"},
                {239, "two hundred thirty-nine dollars"},
                {240, "two hundred forty dollars"},
                {241, "two hundred forty-one dollars"},
                {242, "two hundred forty-two dollars"},
                {243, "two hundred forty-three dollars"},
                {244, "two hundred forty-four dollars"},
                {245, "two hundred forty-five dollars"},
                {246, "two hundred forty-six dollars"},
                {247, "two hundred forty-seven dollars"},
                {248, "two hundred forty-eight dollars"},
                {249, "two hundred forty-nine dollars"},
                {250, "two hundred fifty dollars"},
                {251, "two hundred fifty-one dollars"},
                {252, "two hundred fifty-two dollars"},
                {253, "two hundred fifty-three dollars"},
                {254, "two hundred fifty-four dollars"},
                {255, "two hundred fifty-five dollars"},
                {256, "two hundred fifty-six dollars"},
                {257, "two hundred fifty-seven dollars"},
                {258, "two hundred fifty-eight dollars"},
                {259, "two hundred fifty-nine dollars"},
                {260, "two hundred sixty dollars"},
                {261, "two hundred sixty-one dollars"},
                {262, "two hundred sixty-two dollars"},
                {263, "two hundred sixty-three dollars"},
                {264, "two hundred sixty-four dollars"},
                {265, "two hundred sixty-five dollars"},
                {266, "two hundred sixty-six dollars"},
                {267, "two hundred sixty-seven dollars"},
                {268, "two hundred sixty-eight dollars"},
                {269, "two hundred sixty-nine dollars"},
                {270, "two hundred seventy dollars"},
                {271, "two hundred seventy-one dollars"},
                {272, "two hundred seventy-two dollars"},
                {273, "two hundred seventy-three dollars"},
                {274, "two hundred seventy-four dollars"},
                {275, "two hundred seventy-five dollars"},
                {276, "two hundred seventy-six dollars"},
                {277, "two hundred seventy-seven dollars"},
                {278, "two hundred seventy-eight dollars"},
                {279, "two hundred seventy-nine dollars"},
                {280, "two hundred eighty dollars"},
                {281, "two hundred eighty-one dollars"},
                {282, "two hundred eighty-two dollars"},
                {283, "two hundred eighty-three dollars"},
                {284, "two hundred eighty-four dollars"},
                {285, "two hundred eighty-five dollars"},
                {286, "two hundred eighty-six dollars"},
                {287, "two hundred eighty-seven dollars"},
                {288, "two hundred eighty-eight dollars"},
                {289, "two hundred eighty-nine dollars"},
                {290, "two hundred ninety dollars"},
                {291, "two hundred ninety-one dollars"},
                {292, "two hundred ninety-two dollars"},
                {293, "two hundred ninety-three dollars"},
                {294, "two hundred ninety-four dollars"},
                {295, "two hundred ninety-five dollars"},
                {296, "two hundred ninety-six dollars"},
                {297, "two hundred ninety-seven dollars"},
                {298, "two hundred ninety-eight dollars"},
                {299, "two hundred ninety-nine dollars"},
                {300, "three hundred dollars"},
                {301, "three hundred one dollars"},
                {302, "three hundred two dollars"},
                {303, "three hundred three dollars"},
                {304, "three hundred four dollars"},
                {305, "three hundred five dollars"},
                {306, "three hundred six dollars"},
                {307, "three hundred seven dollars"},
                {308, "three hundred eight dollars"},
                {309, "three hundred nine dollars"},
                {310, "three hundred ten dollars"},
                {311, "three hundred eleven dollars"},
                {312, "three hundred twelve dollars"},
                {313, "three hundred thirteen dollars"},
                {314, "three hundred fourteen dollars"},
                {315, "three hundred fifteen dollars"},
                {316, "three hundred sixteen dollars"},
                {317, "three hundred seventeen dollars"},
                {318, "three hundred eighteen dollars"},
                {319, "three hundred nineteen dollars"},
                {320, "three hundred twenty dollars"},
                {321, "three hundred twenty-one dollars"},
                {322, "three hundred twenty-two dollars"},
                {323, "three hundred twenty-three dollars"},
                {324, "three hundred twenty-four dollars"},
                {325, "three hundred twenty-five dollars"},
                {326, "three hundred twenty-six dollars"},
                {327, "three hundred twenty-seven dollars"},
                {328, "three hundred twenty-eight dollars"},
                {329, "three hundred twenty-nine dollars"},
                {330, "three hundred thirty dollars"},
                {331, "three hundred thirty-one dollars"},
                {332, "three hundred thirty-two dollars"},
                {333, "three hundred thirty-three dollars"},
                {334, "three hundred thirty-four dollars"},
                {335, "three hundred thirty-five dollars"},
                {336, "three hundred thirty-six dollars"},
                {337, "three hundred thirty-seven dollars"},
                {338, "three hundred thirty-eight dollars"},
                {339, "three hundred thirty-nine dollars"},
                {340, "three hundred forty dollars"},
                {341, "three hundred forty-one dollars"},
                {342, "three hundred forty-two dollars"},
                {343, "three hundred forty-three dollars"},
                {344, "three hundred forty-four dollars"},
                {345, "three hundred forty-five dollars"},
                {346, "three hundred forty-six dollars"},
                {347, "three hundred forty-seven dollars"},
                {348, "three hundred forty-eight dollars"},
                {349, "three hundred forty-nine dollars"},
                {350, "three hundred fifty dollars"},
                {351, "three hundred fifty-one dollars"},
                {352, "three hundred fifty-two dollars"},
                {353, "three hundred fifty-three dollars"},
                {354, "three hundred fifty-four dollars"},
                {355, "three hundred fifty-five dollars"},
                {356, "three hundred fifty-six dollars"},
                {357, "three hundred fifty-seven dollars"},
                {358, "three hundred fifty-eight dollars"},
                {359, "three hundred fifty-nine dollars"},
                {360, "three hundred sixty dollars"},
                {361, "three hundred sixty-one dollars"},
                {362, "three hundred sixty-two dollars"},
                {363, "three hundred sixty-three dollars"},
                {364, "three hundred sixty-four dollars"},
                {365, "three hundred sixty-five dollars"},
                {366, "three hundred sixty-six dollars"},
                {367, "three hundred sixty-seven dollars"},
                {368, "three hundred sixty-eight dollars"},
                {369, "three hundred sixty-nine dollars"},
                {370, "three hundred seventy dollars"},
                {371, "three hundred seventy-one dollars"},
                {372, "three hundred seventy-two dollars"},
                {373, "three hundred seventy-three dollars"},
                {374, "three hundred seventy-four dollars"},
                {375, "three hundred seventy-five dollars"},
                {376, "three hundred seventy-six dollars"},
                {377, "three hundred seventy-seven dollars"},
                {378, "three hundred seventy-eight dollars"},
                {379, "three hundred seventy-nine dollars"},
                {380, "three hundred eighty dollars"},
                {381, "three hundred eighty-one dollars"},
                {382, "three hundred eighty-two dollars"},
                {383, "three hundred eighty-three dollars"},
                {384, "three hundred eighty-four dollars"},
                {385, "three hundred eighty-five dollars"},
                {386, "three hundred eighty-six dollars"},
                {387, "three hundred eighty-seven dollars"},
                {388, "three hundred eighty-eight dollars"},
                {389, "three hundred eighty-nine dollars"},
                {390, "three hundred ninety dollars"},
                {391, "three hundred ninety-one dollars"},
                {392, "three hundred ninety-two dollars"},
                {393, "three hundred ninety-three dollars"},
                {394, "three hundred ninety-four dollars"},
                {395, "three hundred ninety-five dollars"},
                {396, "three hundred ninety-six dollars"},
                {397, "three hundred ninety-seven dollars"},
                {398, "three hundred ninety-eight dollars"},
                {399, "three hundred ninety-nine dollars"},
                {400, "four hundred dollars"},
                {401, "four hundred one dollars"},
                {402, "four hundred two dollars"},
                {403, "four hundred three dollars"},
                {404, "four hundred four dollars"},
                {405, "four hundred five dollars"},
                {406, "four hundred six dollars"},
                {407, "four hundred seven dollars"},
                {408, "four hundred eight dollars"},
                {409, "four hundred nine dollars"},
                {410, "four hundred ten dollars"},
                {411, "four hundred eleven dollars"},
                {412, "four hundred twelve dollars"},
                {413, "four hundred thirteen dollars"},
                {414, "four hundred fourteen dollars"},
                {415, "four hundred fifteen dollars"},
                {416, "four hundred sixteen dollars"},
                {417, "four hundred seventeen dollars"},
                {418, "four hundred eighteen dollars"},
                {419, "four hundred nineteen dollars"},
                {420, "four hundred twenty dollars"},
                {421, "four hundred twenty-one dollars"},
                {422, "four hundred twenty-two dollars"},
                {423, "four hundred twenty-three dollars"},
                {424, "four hundred twenty-four dollars"},
                {425, "four hundred twenty-five dollars"},
                {426, "four hundred twenty-six dollars"},
                {427, "four hundred twenty-seven dollars"},
                {428, "four hundred twenty-eight dollars"},
                {429, "four hundred twenty-nine dollars"},
                {430, "four hundred thirty dollars"},
                {431, "four hundred thirty-one dollars"},
                {432, "four hundred thirty-two dollars"},
                {433, "four hundred thirty-three dollars"},
                {434, "four hundred thirty-four dollars"},
                {435, "four hundred thirty-five dollars"},
                {436, "four hundred thirty-six dollars"},
                {437, "four hundred thirty-seven dollars"},
                {438, "four hundred thirty-eight dollars"},
                {439, "four hundred thirty-nine dollars"},
                {440, "four hundred forty dollars"},
                {441, "four hundred forty-one dollars"},
                {442, "four hundred forty-two dollars"},
                {443, "four hundred forty-three dollars"},
                {444, "four hundred forty-four dollars"},
                {445, "four hundred forty-five dollars"},
                {446, "four hundred forty-six dollars"},
                {447, "four hundred forty-seven dollars"},
                {448, "four hundred forty-eight dollars"},
                {449, "four hundred forty-nine dollars"},
                {450, "four hundred fifty dollars"},
                {451, "four hundred fifty-one dollars"},
                {452, "four hundred fifty-two dollars"},
                {453, "four hundred fifty-three dollars"},
                {454, "four hundred fifty-four dollars"},
                {455, "four hundred fifty-five dollars"},
                {456, "four hundred fifty-six dollars"},
                {457, "four hundred fifty-seven dollars"},
                {458, "four hundred fifty-eight dollars"},
                {459, "four hundred fifty-nine dollars"},
                {460, "four hundred sixty dollars"},
                {461, "four hundred sixty-one dollars"},
                {462, "four hundred sixty-two dollars"},
                {463, "four hundred sixty-three dollars"},
                {464, "four hundred sixty-four dollars"},
                {465, "four hundred sixty-five dollars"},
                {466, "four hundred sixty-six dollars"},
                {467, "four hundred sixty-seven dollars"},
                {468, "four hundred sixty-eight dollars"},
                {469, "four hundred sixty-nine dollars"},
                {470, "four hundred seventy dollars"},
                {471, "four hundred seventy-one dollars"},
                {472, "four hundred seventy-two dollars"},
                {473, "four hundred seventy-three dollars"},
                {474, "four hundred seventy-four dollars"},
                {475, "four hundred seventy-five dollars"},
                {476, "four hundred seventy-six dollars"},
                {477, "four hundred seventy-seven dollars"},
                {478, "four hundred seventy-eight dollars"},
                {479, "four hundred seventy-nine dollars"},
                {480, "four hundred eighty dollars"},
                {481, "four hundred eighty-one dollars"},
                {482, "four hundred eighty-two dollars"},
                {483, "four hundred eighty-three dollars"},
                {484, "four hundred eighty-four dollars"},
                {485, "four hundred eighty-five dollars"},
                {486, "four hundred eighty-six dollars"},
                {487, "four hundred eighty-seven dollars"},
                {488, "four hundred eighty-eight dollars"},
                {489, "four hundred eighty-nine dollars"},
                {490, "four hundred ninety dollars"},
                {491, "four hundred ninety-one dollars"},
                {492, "four hundred ninety-two dollars"},
                {493, "four hundred ninety-three dollars"},
                {494, "four hundred ninety-four dollars"},
                {495, "four hundred ninety-five dollars"},
                {496, "four hundred ninety-six dollars"},
                {497, "four hundred ninety-seven dollars"},
                {498, "four hundred ninety-eight dollars"},
                {499, "four hundred ninety-nine dollars"},
                {500, "five hundred dollars"},
                {501, "five hundred one dollars"},
                {502, "five hundred two dollars"},
                {503, "five hundred three dollars"},
                {504, "five hundred four dollars"},
                {505, "five hundred five dollars"},
                {506, "five hundred six dollars"},
                {507, "five hundred seven dollars"},
                {508, "five hundred eight dollars"},
                {509, "five hundred nine dollars"},
                {510, "five hundred ten dollars"},
                {511, "five hundred eleven dollars"},
                {512, "five hundred twelve dollars"},
                {513, "five hundred thirteen dollars"},
                {514, "five hundred fourteen dollars"},
                {515, "five hundred fifteen dollars"},
                {516, "five hundred sixteen dollars"},
                {517, "five hundred seventeen dollars"},
                {518, "five hundred eighteen dollars"},
                {519, "five hundred nineteen dollars"},
                {520, "five hundred twenty dollars"},
                {521, "five hundred twenty-one dollars"},
                {522, "five hundred twenty-two dollars"},
                {523, "five hundred twenty-three dollars"},
                {524, "five hundred twenty-four dollars"},
                {525, "five hundred twenty-five dollars"},
                {526, "five hundred twenty-six dollars"},
                {527, "five hundred twenty-seven dollars"},
                {528, "five hundred twenty-eight dollars"},
                {529, "five hundred twenty-nine dollars"},
                {530, "five hundred thirty dollars"},
                {531, "five hundred thirty-one dollars"},
                {532, "five hundred thirty-two dollars"},
                {533, "five hundred thirty-three dollars"},
                {534, "five hundred thirty-four dollars"},
                {535, "five hundred thirty-five dollars"},
                {536, "five hundred thirty-six dollars"},
                {537, "five hundred thirty-seven dollars"},
                {538, "five hundred thirty-eight dollars"},
                {539, "five hundred thirty-nine dollars"},
                {540, "five hundred forty dollars"},
                {541, "five hundred forty-one dollars"},
                {542, "five hundred forty-two dollars"},
                {543, "five hundred forty-three dollars"},
                {544, "five hundred forty-four dollars"},
                {545, "five hundred forty-five dollars"},
                {546, "five hundred forty-six dollars"},
                {547, "five hundred forty-seven dollars"},
                {548, "five hundred forty-eight dollars"},
                {549, "five hundred forty-nine dollars"},
                {550, "five hundred fifty dollars"},
                {551, "five hundred fifty-one dollars"},
                {552, "five hundred fifty-two dollars"},
                {553, "five hundred fifty-three dollars"},
                {554, "five hundred fifty-four dollars"},
                {555, "five hundred fifty-five dollars"},
                {556, "five hundred fifty-six dollars"},
                {557, "five hundred fifty-seven dollars"},
                {558, "five hundred fifty-eight dollars"},
                {559, "five hundred fifty-nine dollars"},
                {560, "five hundred sixty dollars"},
                {561, "five hundred sixty-one dollars"},
                {562, "five hundred sixty-two dollars"},
                {563, "five hundred sixty-three dollars"},
                {564, "five hundred sixty-four dollars"},
                {565, "five hundred sixty-five dollars"},
                {566, "five hundred sixty-six dollars"},
                {567, "five hundred sixty-seven dollars"},
                {568, "five hundred sixty-eight dollars"},
                {569, "five hundred sixty-nine dollars"},
                {570, "five hundred seventy dollars"},
                {571, "five hundred seventy-one dollars"},
                {572, "five hundred seventy-two dollars"},
                {573, "five hundred seventy-three dollars"},
                {574, "five hundred seventy-four dollars"},
                {575, "five hundred seventy-five dollars"},
                {576, "five hundred seventy-six dollars"},
                {577, "five hundred seventy-seven dollars"},
                {578, "five hundred seventy-eight dollars"},
                {579, "five hundred seventy-nine dollars"},
                {580, "five hundred eighty dollars"},
                {581, "five hundred eighty-one dollars"},
                {582, "five hundred eighty-two dollars"},
                {583, "five hundred eighty-three dollars"},
                {584, "five hundred eighty-four dollars"},
                {585, "five hundred eighty-five dollars"},
                {586, "five hundred eighty-six dollars"},
                {587, "five hundred eighty-seven dollars"},
                {588, "five hundred eighty-eight dollars"},
                {589, "five hundred eighty-nine dollars"},
                {590, "five hundred ninety dollars"},
                {591, "five hundred ninety-one dollars"},
                {592, "five hundred ninety-two dollars"},
                {593, "five hundred ninety-three dollars"},
                {594, "five hundred ninety-four dollars"},
                {595, "five hundred ninety-five dollars"},
                {596, "five hundred ninety-six dollars"},
                {597, "five hundred ninety-seven dollars"},
                {598, "five hundred ninety-eight dollars"},
                {599, "five hundred ninety-nine dollars"},
                {600, "six hundred dollars"},
                {601, "six hundred one dollars"},
                {602, "six hundred two dollars"},
                {603, "six hundred three dollars"},
                {604, "six hundred four dollars"},
                {605, "six hundred five dollars"},
                {606, "six hundred six dollars"},
                {607, "six hundred seven dollars"},
                {608, "six hundred eight dollars"},
                {609, "six hundred nine dollars"},
                {610, "six hundred ten dollars"},
                {611, "six hundred eleven dollars"},
                {612, "six hundred twelve dollars"},
                {613, "six hundred thirteen dollars"},
                {614, "six hundred fourteen dollars"},
                {615, "six hundred fifteen dollars"},
                {616, "six hundred sixteen dollars"},
                {617, "six hundred seventeen dollars"},
                {618, "six hundred eighteen dollars"},
                {619, "six hundred nineteen dollars"},
                {620, "six hundred twenty dollars"},
                {621, "six hundred twenty-one dollars"},
                {622, "six hundred twenty-two dollars"},
                {623, "six hundred twenty-three dollars"},
                {624, "six hundred twenty-four dollars"},
                {625, "six hundred twenty-five dollars"},
                {626, "six hundred twenty-six dollars"},
                {627, "six hundred twenty-seven dollars"},
                {628, "six hundred twenty-eight dollars"},
                {629, "six hundred twenty-nine dollars"},
                {630, "six hundred thirty dollars"},
                {631, "six hundred thirty-one dollars"},
                {632, "six hundred thirty-two dollars"},
                {633, "six hundred thirty-three dollars"},
                {634, "six hundred thirty-four dollars"},
                {635, "six hundred thirty-five dollars"},
                {636, "six hundred thirty-six dollars"},
                {637, "six hundred thirty-seven dollars"},
                {638, "six hundred thirty-eight dollars"},
                {639, "six hundred thirty-nine dollars"},
                {640, "six hundred forty dollars"},
                {641, "six hundred forty-one dollars"},
                {642, "six hundred forty-two dollars"},
                {643, "six hundred forty-three dollars"},
                {644, "six hundred forty-four dollars"},
                {645, "six hundred forty-five dollars"},
                {646, "six hundred forty-six dollars"},
                {647, "six hundred forty-seven dollars"},
                {648, "six hundred forty-eight dollars"},
                {649, "six hundred forty-nine dollars"},
                {650, "six hundred fifty dollars"},
                {651, "six hundred fifty-one dollars"},
                {652, "six hundred fifty-two dollars"},
                {653, "six hundred fifty-three dollars"},
                {654, "six hundred fifty-four dollars"},
                {655, "six hundred fifty-five dollars"},
                {656, "six hundred fifty-six dollars"},
                {657, "six hundred fifty-seven dollars"},
                {658, "six hundred fifty-eight dollars"},
                {659, "six hundred fifty-nine dollars"},
                {660, "six hundred sixty dollars"},
                {661, "six hundred sixty-one dollars"},
                {662, "six hundred sixty-two dollars"},
                {663, "six hundred sixty-three dollars"},
                {664, "six hundred sixty-four dollars"},
                {665, "six hundred sixty-five dollars"},
                {666, "six hundred sixty-six dollars"},
                {667, "six hundred sixty-seven dollars"},
                {668, "six hundred sixty-eight dollars"},
                {669, "six hundred sixty-nine dollars"},
                {670, "six hundred seventy dollars"},
                {671, "six hundred seventy-one dollars"},
                {672, "six hundred seventy-two dollars"},
                {673, "six hundred seventy-three dollars"},
                {674, "six hundred seventy-four dollars"},
                {675, "six hundred seventy-five dollars"},
                {676, "six hundred seventy-six dollars"},
                {677, "six hundred seventy-seven dollars"},
                {678, "six hundred seventy-eight dollars"},
                {679, "six hundred seventy-nine dollars"},
                {680, "six hundred eighty dollars"},
                {681, "six hundred eighty-one dollars"},
                {682, "six hundred eighty-two dollars"},
                {683, "six hundred eighty-three dollars"},
                {684, "six hundred eighty-four dollars"},
                {685, "six hundred eighty-five dollars"},
                {686, "six hundred eighty-six dollars"},
                {687, "six hundred eighty-seven dollars"},
                {688, "six hundred eighty-eight dollars"},
                {689, "six hundred eighty-nine dollars"},
                {690, "six hundred ninety dollars"},
                {691, "six hundred ninety-one dollars"},
                {692, "six hundred ninety-two dollars"},
                {693, "six hundred ninety-three dollars"},
                {694, "six hundred ninety-four dollars"},
                {695, "six hundred ninety-five dollars"},
                {696, "six hundred ninety-six dollars"},
                {697, "six hundred ninety-seven dollars"},
                {698, "six hundred ninety-eight dollars"},
                {699, "six hundred ninety-nine dollars"},
                {700, "seven hundred dollars"},
                {701, "seven hundred one dollars"},
                {702, "seven hundred two dollars"},
                {703, "seven hundred three dollars"},
                {704, "seven hundred four dollars"},
                {705, "seven hundred five dollars"},
                {706, "seven hundred six dollars"},
                {707, "seven hundred seven dollars"},
                {708, "seven hundred eight dollars"},
                {709, "seven hundred nine dollars"},
                {710, "seven hundred ten dollars"},
                {711, "seven hundred eleven dollars"},
                {712, "seven hundred twelve dollars"},
                {713, "seven hundred thirteen dollars"},
                {714, "seven hundred fourteen dollars"},
                {715, "seven hundred fifteen dollars"},
                {716, "seven hundred sixteen dollars"},
                {717, "seven hundred seventeen dollars"},
                {718, "seven hundred eighteen dollars"},
                {719, "seven hundred nineteen dollars"},
                {720, "seven hundred twenty dollars"},
                {721, "seven hundred twenty-one dollars"},
                {722, "seven hundred twenty-two dollars"},
                {723, "seven hundred twenty-three dollars"},
                {724, "seven hundred twenty-four dollars"},
                {725, "seven hundred twenty-five dollars"},
                {726, "seven hundred twenty-six dollars"},
                {727, "seven hundred twenty-seven dollars"},
                {728, "seven hundred twenty-eight dollars"},
                {729, "seven hundred twenty-nine dollars"},
                {730, "seven hundred thirty dollars"},
                {731, "seven hundred thirty-one dollars"},
                {732, "seven hundred thirty-two dollars"},
                {733, "seven hundred thirty-three dollars"},
                {734, "seven hundred thirty-four dollars"},
                {735, "seven hundred thirty-five dollars"},
                {736, "seven hundred thirty-six dollars"},
                {737, "seven hundred thirty-seven dollars"},
                {738, "seven hundred thirty-eight dollars"},
                {739, "seven hundred thirty-nine dollars"},
                {740, "seven hundred forty dollars"},
                {741, "seven hundred forty-one dollars"},
                {742, "seven hundred forty-two dollars"},
                {743, "seven hundred forty-three dollars"},
                {744, "seven hundred forty-four dollars"},
                {745, "seven hundred forty-five dollars"},
                {746, "seven hundred forty-six dollars"},
                {747, "seven hundred forty-seven dollars"},
                {748, "seven hundred forty-eight dollars"},
                {749, "seven hundred forty-nine dollars"},
                {750, "seven hundred fifty dollars"},
                {751, "seven hundred fifty-one dollars"},
                {752, "seven hundred fifty-two dollars"},
                {753, "seven hundred fifty-three dollars"},
                {754, "seven hundred fifty-four dollars"},
                {755, "seven hundred fifty-five dollars"},
                {756, "seven hundred fifty-six dollars"},
                {757, "seven hundred fifty-seven dollars"},
                {758, "seven hundred fifty-eight dollars"},
                {759, "seven hundred fifty-nine dollars"},
                {760, "seven hundred sixty dollars"},
                {761, "seven hundred sixty-one dollars"},
                {762, "seven hundred sixty-two dollars"},
                {763, "seven hundred sixty-three dollars"},
                {764, "seven hundred sixty-four dollars"},
                {765, "seven hundred sixty-five dollars"},
                {766, "seven hundred sixty-six dollars"},
                {767, "seven hundred sixty-seven dollars"},
                {768, "seven hundred sixty-eight dollars"},
                {769, "seven hundred sixty-nine dollars"},
                {770, "seven hundred seventy dollars"},
                {771, "seven hundred seventy-one dollars"},
                {772, "seven hundred seventy-two dollars"},
                {773, "seven hundred seventy-three dollars"},
                {774, "seven hundred seventy-four dollars"},
                {775, "seven hundred seventy-five dollars"},
                {776, "seven hundred seventy-six dollars"},
                {777, "seven hundred seventy-seven dollars"},
                {778, "seven hundred seventy-eight dollars"},
                {779, "seven hundred seventy-nine dollars"},
                {780, "seven hundred eighty dollars"},
                {781, "seven hundred eighty-one dollars"},
                {782, "seven hundred eighty-two dollars"},
                {783, "seven hundred eighty-three dollars"},
                {784, "seven hundred eighty-four dollars"},
                {785, "seven hundred eighty-five dollars"},
                {786, "seven hundred eighty-six dollars"},
                {787, "seven hundred eighty-seven dollars"},
                {788, "seven hundred eighty-eight dollars"},
                {789, "seven hundred eighty-nine dollars"},
                {790, "seven hundred ninety dollars"},
                {791, "seven hundred ninety-one dollars"},
                {792, "seven hundred ninety-two dollars"},
                {793, "seven hundred ninety-three dollars"},
                {794, "seven hundred ninety-four dollars"},
                {795, "seven hundred ninety-five dollars"},
                {796, "seven hundred ninety-six dollars"},
                {797, "seven hundred ninety-seven dollars"},
                {798, "seven hundred ninety-eight dollars"},
                {799, "seven hundred ninety-nine dollars"},
                {800, "eight hundred dollars"},
                {801, "eight hundred one dollars"},
                {802, "eight hundred two dollars"},
                {803, "eight hundred three dollars"},
                {804, "eight hundred four dollars"},
                {805, "eight hundred five dollars"},
                {806, "eight hundred six dollars"},
                {807, "eight hundred seven dollars"},
                {808, "eight hundred eight dollars"},
                {809, "eight hundred nine dollars"},
                {810, "eight hundred ten dollars"},
                {811, "eight hundred eleven dollars"},
                {812, "eight hundred twelve dollars"},
                {813, "eight hundred thirteen dollars"},
                {814, "eight hundred fourteen dollars"},
                {815, "eight hundred fifteen dollars"},
                {816, "eight hundred sixteen dollars"},
                {817, "eight hundred seventeen dollars"},
                {818, "eight hundred eighteen dollars"},
                {819, "eight hundred nineteen dollars"},
                {820, "eight hundred twenty dollars"},
                {821, "eight hundred twenty-one dollars"},
                {822, "eight hundred twenty-two dollars"},
                {823, "eight hundred twenty-three dollars"},
                {824, "eight hundred twenty-four dollars"},
                {825, "eight hundred twenty-five dollars"},
                {826, "eight hundred twenty-six dollars"},
                {827, "eight hundred twenty-seven dollars"},
                {828, "eight hundred twenty-eight dollars"},
                {829, "eight hundred twenty-nine dollars"},
                {830, "eight hundred thirty dollars"},
                {831, "eight hundred thirty-one dollars"},
                {832, "eight hundred thirty-two dollars"},
                {833, "eight hundred thirty-three dollars"},
                {834, "eight hundred thirty-four dollars"},
                {835, "eight hundred thirty-five dollars"},
                {836, "eight hundred thirty-six dollars"},
                {837, "eight hundred thirty-seven dollars"},
                {838, "eight hundred thirty-eight dollars"},
                {839, "eight hundred thirty-nine dollars"},
                {840, "eight hundred forty dollars"},
                {841, "eight hundred forty-one dollars"},
                {842, "eight hundred forty-two dollars"},
                {843, "eight hundred forty-three dollars"},
                {844, "eight hundred forty-four dollars"},
                {845, "eight hundred forty-five dollars"},
                {846, "eight hundred forty-six dollars"},
                {847, "eight hundred forty-seven dollars"},
                {848, "eight hundred forty-eight dollars"},
                {849, "eight hundred forty-nine dollars"},
                {850, "eight hundred fifty dollars"},
                {851, "eight hundred fifty-one dollars"},
                {852, "eight hundred fifty-two dollars"},
                {853, "eight hundred fifty-three dollars"},
                {854, "eight hundred fifty-four dollars"},
                {855, "eight hundred fifty-five dollars"},
                {856, "eight hundred fifty-six dollars"},
                {857, "eight hundred fifty-seven dollars"},
                {858, "eight hundred fifty-eight dollars"},
                {859, "eight hundred fifty-nine dollars"},
                {860, "eight hundred sixty dollars"},
                {861, "eight hundred sixty-one dollars"},
                {862, "eight hundred sixty-two dollars"},
                {863, "eight hundred sixty-three dollars"},
                {864, "eight hundred sixty-four dollars"},
                {865, "eight hundred sixty-five dollars"},
                {866, "eight hundred sixty-six dollars"},
                {867, "eight hundred sixty-seven dollars"},
                {868, "eight hundred sixty-eight dollars"},
                {869, "eight hundred sixty-nine dollars"},
                {870, "eight hundred seventy dollars"},
                {871, "eight hundred seventy-one dollars"},
                {872, "eight hundred seventy-two dollars"},
                {873, "eight hundred seventy-three dollars"},
                {874, "eight hundred seventy-four dollars"},
                {875, "eight hundred seventy-five dollars"},
                {876, "eight hundred seventy-six dollars"},
                {877, "eight hundred seventy-seven dollars"},
                {878, "eight hundred seventy-eight dollars"},
                {879, "eight hundred seventy-nine dollars"},
                {880, "eight hundred eighty dollars"},
                {881, "eight hundred eighty-one dollars"},
                {882, "eight hundred eighty-two dollars"},
                {883, "eight hundred eighty-three dollars"},
                {884, "eight hundred eighty-four dollars"},
                {885, "eight hundred eighty-five dollars"},
                {886, "eight hundred eighty-six dollars"},
                {887, "eight hundred eighty-seven dollars"},
                {888, "eight hundred eighty-eight dollars"},
                {889, "eight hundred eighty-nine dollars"},
                {890, "eight hundred ninety dollars"},
                {891, "eight hundred ninety-one dollars"},
                {892, "eight hundred ninety-two dollars"},
                {893, "eight hundred ninety-three dollars"},
                {894, "eight hundred ninety-four dollars"},
                {895, "eight hundred ninety-five dollars"},
                {896, "eight hundred ninety-six dollars"},
                {897, "eight hundred ninety-seven dollars"},
                {898, "eight hundred ninety-eight dollars"},
                {899, "eight hundred ninety-nine dollars"},
                {900, "nine hundred dollars"},
                {901, "nine hundred one dollars"},
                {902, "nine hundred two dollars"},
                {903, "nine hundred three dollars"},
                {904, "nine hundred four dollars"},
                {905, "nine hundred five dollars"},
                {906, "nine hundred six dollars"},
                {907, "nine hundred seven dollars"},
                {908, "nine hundred eight dollars"},
                {909, "nine hundred nine dollars"},
                {910, "nine hundred ten dollars"},
                {911, "nine hundred eleven dollars"},
                {912, "nine hundred twelve dollars"},
                {913, "nine hundred thirteen dollars"},
                {914, "nine hundred fourteen dollars"},
                {915, "nine hundred fifteen dollars"},
                {916, "nine hundred sixteen dollars"},
                {917, "nine hundred seventeen dollars"},
                {918, "nine hundred eighteen dollars"},
                {919, "nine hundred nineteen dollars"},
                {920, "nine hundred twenty dollars"},
                {921, "nine hundred twenty-one dollars"},
                {922, "nine hundred twenty-two dollars"},
                {923, "nine hundred twenty-three dollars"},
                {924, "nine hundred twenty-four dollars"},
                {925, "nine hundred twenty-five dollars"},
                {926, "nine hundred twenty-six dollars"},
                {927, "nine hundred twenty-seven dollars"},
                {928, "nine hundred twenty-eight dollars"},
                {929, "nine hundred twenty-nine dollars"},
                {930, "nine hundred thirty dollars"},
                {931, "nine hundred thirty-one dollars"},
                {932, "nine hundred thirty-two dollars"},
                {933, "nine hundred thirty-three dollars"},
                {934, "nine hundred thirty-four dollars"},
                {935, "nine hundred thirty-five dollars"},
                {936, "nine hundred thirty-six dollars"},
                {937, "nine hundred thirty-seven dollars"},
                {938, "nine hundred thirty-eight dollars"},
                {939, "nine hundred thirty-nine dollars"},
                {940, "nine hundred forty dollars"},
                {941, "nine hundred forty-one dollars"},
                {942, "nine hundred forty-two dollars"},
                {943, "nine hundred forty-three dollars"},
                {944, "nine hundred forty-four dollars"},
                {945, "nine hundred forty-five dollars"},
                {946, "nine hundred forty-six dollars"},
                {947, "nine hundred forty-seven dollars"},
                {948, "nine hundred forty-eight dollars"},
                {949, "nine hundred forty-nine dollars"},
                {950, "nine hundred fifty dollars"},
                {951, "nine hundred fifty-one dollars"},
                {952, "nine hundred fifty-two dollars"},
                {953, "nine hundred fifty-three dollars"},
                {954, "nine hundred fifty-four dollars"},
                {955, "nine hundred fifty-five dollars"},
                {956, "nine hundred fifty-six dollars"},
                {957, "nine hundred fifty-seven dollars"},
                {958, "nine hundred fifty-eight dollars"},
                {959, "nine hundred fifty-nine dollars"},
                {960, "nine hundred sixty dollars"},
                {961, "nine hundred sixty-one dollars"},
                {962, "nine hundred sixty-two dollars"},
                {963, "nine hundred sixty-three dollars"},
                {964, "nine hundred sixty-four dollars"},
                {965, "nine hundred sixty-five dollars"},
                {966, "nine hundred sixty-six dollars"},
                {967, "nine hundred sixty-seven dollars"},
                {968, "nine hundred sixty-eight dollars"},
                {969, "nine hundred sixty-nine dollars"},
                {970, "nine hundred seventy dollars"},
                {971, "nine hundred seventy-one dollars"},
                {972, "nine hundred seventy-two dollars"},
                {973, "nine hundred seventy-three dollars"},
                {974, "nine hundred seventy-four dollars"},
                {975, "nine hundred seventy-five dollars"},
                {976, "nine hundred seventy-six dollars"},
                {977, "nine hundred seventy-seven dollars"},
                {978, "nine hundred seventy-eight dollars"},
                {979, "nine hundred seventy-nine dollars"},
                {980, "nine hundred eighty dollars"},
                {981, "nine hundred eighty-one dollars"},
                {982, "nine hundred eighty-two dollars"},
                {983, "nine hundred eighty-three dollars"},
                {984, "nine hundred eighty-four dollars"},
                {985, "nine hundred eighty-five dollars"},
                {986, "nine hundred eighty-six dollars"},
                {987, "nine hundred eighty-seven dollars"},
                {988, "nine hundred eighty-eight dollars"},
                {989, "nine hundred eighty-nine dollars"},
                {990, "nine hundred ninety dollars"},
                {991, "nine hundred ninety-one dollars"},
                {992, "nine hundred ninety-two dollars"},
                {993, "nine hundred ninety-three dollars"},
                {994, "nine hundred ninety-four dollars"},
                {995, "nine hundred ninety-five dollars"},
                {996, "nine hundred ninety-six dollars"},
                {997, "nine hundred ninety-seven dollars"},
                {998, "nine hundred ninety-eight dollars"},
                {999, "nine hundred ninety-nine dollars"},
            };
            var c = new Converter();
            foreach (var test in dict)
            {
                var result = c.ToWords(test.Key);
                Assert.AreEqual(test.Value, result);
            }
        }
    }
}